USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINTECH_DW;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE LOAD_AUDIT (
  source_table      STRING,
  file_name         STRING,
  loaded_at         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  row_count_loaded  NUMBER
);
